---
- name: Retrieve template default parameters from template ID
  ansible.builtin.include_vars:
    file: "{{ cluster_settings_template_id }}.yml"

- name: Get default pull-secret and ssh-key
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ cluster_settings_default_credentials_secret_name }}"
    namespace: "{{ cluster_settings_default_credentials_secret_namespace }}"
  register: default_cluster_credentials
  when: cluster_settings_template_parameters.ssh_key is not defined or cluster_settings_template_parameters.pull_secret is not defined
  no_log: true

- name: Set default pull-secret and ssh-key as template default parameters
  ansible.builtin.set_fact:
    cluster_settings_template_defaults: >
      {{ cluster_settings_template_defaults | combine({
          'pull_secret': '{{ default_cluster_credentials.resources[0].data.pull_secret }}',
          'ssh_key': '{{ default_cluster_credentials.resources[0].data.ssh_key_pub }}'
          })
      }}
  when: cluster_settings_template_parameters.ssh_key is not defined or cluster_settings_template_parameters.pull_secret is not defined
  no_log: true

- name: Merge default template parameters with user-provided template parameters
  ansible.builtin.set_fact:
    cluster_settings_template_defaults: >
      {{ cluster_settings_template_defaults | combine(cluster_settings_template_parameters) }}
  when: cluster_settings_template_parameters is defined
  no_log: true

- name: Merge template parameters with read-only settings
  ansible.builtin.set_fact:
    cluster_settings_result: >
      {{ cluster_settings_template_defaults | combine(cluster_settings_result) }}
  no_log: true
