---
argument_specs:
  attach_and_approve_all_new_agents:
    options:
      manage_agents_cluster_order_name:
        type: str
        required: true
      manage_agents_cluster_network:
        type: str

        # XXX: Warning, this is a hack! We need this when *creating* a cluster,
        # but not when *deleting* a cluster, but this task list is called for
        # both workflows.
        required: false
  detach_and_unlabel_all_removed_agents:
    options:
      manage_agents_cluster_order_name:
        type: str
        required: true
      manage_agents_cluster_network:
        type: str
        required: true
      manage_agents_idle_agents_network:
        type: str
        required: true
  select_and_label_new_agents:
    options:
      manage_agents_desired_count:
        type: int
        required: true
      manage_agents_resource_class:
        type: str
        required: true
      manage_agents_cluster_order_name:
        type: str
        required: true
  wait_for_agents_to_be_removed:
    options:
      manage_agents_desired_count:
        type: int
        required: true
      manage_agents_resource_class:
        type: str
        required: true
      manage_agents_cluster_order_name:
        type: str
        required: true
