---
- name: Post-install stack
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get k8s cluster info
      kubernetes.core.k8s_cluster_info:
      register: api_status
    - debug:
        var: api_status
