---
- name: Cloudkit's AAP configuration
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Load extra variables
      ansible.builtin.include_role:
        name: load_extra_vars
      vars:
        load_extra_vars_file_path: "{{ lookup('env', 'CONFIG_AS_CODE_EXTRA_VARS_PATH') }}"

    - name: Configure AAP
      ansible.builtin.include_role:
        name: cloudkit.config_as_code.aap
