---
- name: Cloudkit's AAP configuration
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    config_as_code_extra_vars: "{{ lookup('env', 'CONFIG_AS_CODE_EXTRA_VARS_PATH') }}"

  tasks:
    - name: Load extra vars
      ansible.builtin.include_vars:
        file: "{{ config_as_code_extra_vars }}"

    - name: Configure AAP
      ansible.builtin.include_role:
        name: cloudkit.config_as_code.aap
