---
- name: Cloudkit's AAP configuration
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_instance_name: "{{ lookup('env', 'AAP_INSTANCE_NAME') }}"
    aap_hostname: "{{ lookup('env', 'AAP_HOSTNAME') }}"
    aap_username: "{{ lookup('env', 'AAP_USERNAME') }}"
    aap_password: "{{ lookup('env', 'AAP_PASSWORD') }}"
    aap_validate_certs: "{{ lookup('env', 'AAP_VALIDATE_CERTS') | bool }}"
    aap_organization_name: "{{ lookup('env', 'AAP_ORGANIZATION_NAME') }}"
    aap_project_name: "{{ lookup('env', 'AAP_PROJECT_NAME') }}"
    aap_project_git_uri: "{{ lookup('env', 'AAP_PROJECT_GIT_URI')}}"
    aap_project_git_branch: "{{ lookup('env', 'AAP_PROJECT_GIT_BRANCH') }}"
    aap_ee_image: "{{ lookup('env', 'AAP_EE_IMAGE') }}"
    cloudkit_fulfillment_service_uri: "{{ lookup('env', 'CLOUDKIT_FULFILLMENT_SERVICE_URI') }}"
    cloudkit_template_collections: "{{ lookup('env', 'CLOUDKIT_TEMPLATE_COLLECTIONS') | split(',') }}"

  tasks:
    - name: Configure AAP
      ansible.builtin.include_role:
        name: cloudkit.config_as_code.aap
