- name: Setup subscription
  hosts: localhost
  connection: local

  vars:
    aap_hostname: "{{ lookup('env', 'AAP_HOSTNAME') }}"
    aap_username: "{{ lookup('env', 'AAP_USERNAME') }}"
    aap_password: "{{ lookup('env', 'AAP_PASSWORD') }}"
    aap_validate_certs: "{{ lookup('env', 'AAP_VALIDATE_CERTS') | bool }}"
    license_manifest_path: "{{ lookup('env', 'LICENSE_MANIFEST_PATH') }}"

  tasks:
    - name: Enable AAP license
      ansible.controller.license:
        controller_host: "{{ aap_hostname }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        validate_certs: "{{ aap_validate_certs }}"
        manifest: "{{ license_manifest_path }}"
