- name: Setup subscription
  hosts: localhost
  connection: local

  vars:
    config_as_code_extra_vars: "{{ lookup('env', 'CONFIG_AS_CODE_EXTRA_VARS_PATH') }}"

  tasks:
    - name: Load extra vars
      ansible.builtin.include_vars:
        file: "{{ config_as_code_extra_vars }}"

    - name: Enable AAP license
      ansible.controller.license:
        controller_host: "{{ aap_hostname }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        validate_certs: "{{ aap_validate_certs }}"
        manifest: "{{ license_manifest_path }}"
