namespace: cloudkit
name: config_as_code
version: 1.0.0
readme: README.md
authors:
- Adrien Gentil @adriengentil
description: Cloudkit's AAP configuration as code
license:
- Apache-2.0
tags:
  - infrastructure
repository: https://github.com/innabox/cloudkit-aap
issues: https://github.com/innabox/cloudkit-aap/issues
build_ignore: []
dependencies:
  ansible.platform: "2.5.20250507"
  ansible.hub: "1.0.0"
  ansible.controller: "4.6.12"
  ansible.eda: "2.8.0"
  infra.aap_configuration: "3.3.0"
