---
# Create the controller credential so EDA can trigger job templates
eda_credentials:  # noqa: var-naming[no-role-prefix]
  - name: "{{ aap_eda_service_user_name }}"
    organization: "{{ aap_organization_name }}"
    credential_type: 'Red Hat Ansible Automation Platform'
    inputs:
      username: "{{ aap_eda_service_user_name }}"
      password: "{{ aap_eda_service_user_password }}"
      host: "{{ aap_hostname }}/api/controller/"
  - name: "{{ aap_prefix }}-fulfillment-auth-token"
    organization: "{{ aap_organization_name }}"
    credential_type: 'Token Event Stream'
    inputs:
      http_header_key: "Authorization"
      token: "{{ aap_eda_fulfillment_auth_token }}"

# Create EDA project from the Git repo
eda_projects:  # noqa: var-naming[no-role-prefix]
  - name: "{{ aap_prefix }}-eda"
    organization: "{{ aap_organization_name }}"
    url: "{{ aap_project_git_uri }}"

# Create decision environment
eda_decision_environments:  # noqa: var-naming[no-role-prefix]
  - name: "{{ aap_prefix }}-de"
    organization: "{{ aap_organization_name }}"
    image_url: "registry.redhat.io/ansible-automation-platform-25/de-supported-rhel9:latest"

# Create the event stream
eda_event_streams:
  - name: "{{ aap_prefix }}-fulfillment-ev"
    organization: "{{ aap_organization_name }}"
    credential_name: "{{ aap_prefix }}-fulfillment-auth-token"
    forward_events: true

# Create rulebook activation
eda_rulebook_activations:  # noqa: var-naming[no-role-prefix]
  - name: "{{ aap_prefix }}-cluster-fulfillment"
    organization: "{{ aap_organization_name }}"
    eda_credentials:
      - "{{ aap_eda_service_user_name }}"
    project: "{{ aap_prefix }}-eda"
    rulebook: "cluster_fulfillment.yml"
    decision_environment: "{{ aap_prefix }}-de"
    log_level: info
    k8s_service_name: "{{ aap_prefix }}-eda-service"
    extra_vars:
      job_template_organization: "{{ aap_organization_name }}"
      job_template_prefix: "{{ aap_prefix }}"
    event_streams:
      - event_stream: "{{ aap_prefix }}-fulfillment-ev"
        source_name: "__SOURCE_1"  # Magic, this is the default source name set be AAP
    state: "present"
